name: CD

on:
  push:
    branches: [master]
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force image rebuild'
        required: true
        type: choice
        options: [yes, no]

permissions:
  packages: write
  contents: read

jobs:
  Build:
    name: Build & Push
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        version: [ 'alpine3.15', 'alpine3.16', 'alpine3.17', 'alpine3.18', 'alpine3.19', 'ol8', 'ol9' ]

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare metadata for build
        id: metadata
        run: |
          rev=$(git rev-list --tags --max-count=1)
          version=$(git describe --tags "$rev" | tr -d 'v')

          if [[ -z "$version" ]] ; then
            echo "::error::Can't find version info"
            exit 1
          fi

          docker_file=".docker/${{env.DOCKER_FILE}}.docker"
          base_image=$(grep 'FROM ' $docker_file | grep -v 'builder' | sed 's#${REGISTRY}/##' | tail -1 | cut -f2 -d' ')

          if [[ -z "$base_image" ]] ; then
            echo "::error::Can't extract base image info"
            exit 1
          fi

          echo "version=$version" >> $GITHUB_OUTPUT
          echo "dockerfile=$docker_file" >> $GITHUB_OUTPUT
          echo "baseimage=$base_image" >> $GITHUB_OUTPUT

          echo -e "\033[34mVersion:\033[0m    $version"
          echo -e "\033[34mDockerfile:\033[0m $docker_file"
          echo -e "\033[34mBase image:\033[0m $base_image"
